// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: grpcapi/vmmanager.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VMManager_CreateVM_FullMethodName       = "/grpcapi.VMManager/CreateVM"
	VMManager_StartVM_FullMethodName        = "/grpcapi.VMManager/StartVM"
	VMManager_StopVM_FullMethodName         = "/grpcapi.VMManager/StopVM"
	VMManager_GetVMStatus_FullMethodName    = "/grpcapi.VMManager/GetVMStatus"
	VMManager_SendQMPCommand_FullMethodName = "/grpcapi.VMManager/SendQMPCommand"
)

// VMManagerClient is the client API for VMManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VMManagerClient interface {
	CreateVM(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error)
	StartVM(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error)
	StopVM(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error)
	GetVMStatus(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMStatus, error)
	SendQMPCommand(ctx context.Context, in *QMPCommandRequest, opts ...grpc.CallOption) (*QMPCommandResponse, error)
}

type vMManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewVMManagerClient(cc grpc.ClientConnInterface) VMManagerClient {
	return &vMManagerClient{cc}
}

func (c *vMManagerClient) CreateVM(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMResponse)
	err := c.cc.Invoke(ctx, VMManager_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMManagerClient) StartVM(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMResponse)
	err := c.cc.Invoke(ctx, VMManager_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMManagerClient) StopVM(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMResponse)
	err := c.cc.Invoke(ctx, VMManager_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMManagerClient) GetVMStatus(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStatus)
	err := c.cc.Invoke(ctx, VMManager_GetVMStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMManagerClient) SendQMPCommand(ctx context.Context, in *QMPCommandRequest, opts ...grpc.CallOption) (*QMPCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QMPCommandResponse)
	err := c.cc.Invoke(ctx, VMManager_SendQMPCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMManagerServer is the server API for VMManager service.
// All implementations must embed UnimplementedVMManagerServer
// for forward compatibility.
type VMManagerServer interface {
	CreateVM(context.Context, *VMRequest) (*VMResponse, error)
	StartVM(context.Context, *VMRequest) (*VMResponse, error)
	StopVM(context.Context, *VMRequest) (*VMResponse, error)
	GetVMStatus(context.Context, *VMRequest) (*VMStatus, error)
	SendQMPCommand(context.Context, *QMPCommandRequest) (*QMPCommandResponse, error)
	mustEmbedUnimplementedVMManagerServer()
}

// UnimplementedVMManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMManagerServer struct{}

func (UnimplementedVMManagerServer) CreateVM(context.Context, *VMRequest) (*VMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedVMManagerServer) StartVM(context.Context, *VMRequest) (*VMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedVMManagerServer) StopVM(context.Context, *VMRequest) (*VMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedVMManagerServer) GetVMStatus(context.Context, *VMRequest) (*VMStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVMStatus not implemented")
}
func (UnimplementedVMManagerServer) SendQMPCommand(context.Context, *QMPCommandRequest) (*QMPCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendQMPCommand not implemented")
}
func (UnimplementedVMManagerServer) mustEmbedUnimplementedVMManagerServer() {}
func (UnimplementedVMManagerServer) testEmbeddedByValue()                   {}

// UnsafeVMManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMManagerServer will
// result in compilation errors.
type UnsafeVMManagerServer interface {
	mustEmbedUnimplementedVMManagerServer()
}

func RegisterVMManagerServer(s grpc.ServiceRegistrar, srv VMManagerServer) {
	// If the following call pancis, it indicates UnimplementedVMManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMManager_ServiceDesc, srv)
}

func _VMManager_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMManagerServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMManager_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMManagerServer).CreateVM(ctx, req.(*VMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMManager_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMManagerServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMManager_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMManagerServer).StartVM(ctx, req.(*VMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMManager_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMManagerServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMManager_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMManagerServer).StopVM(ctx, req.(*VMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMManager_GetVMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMManagerServer).GetVMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMManager_GetVMStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMManagerServer).GetVMStatus(ctx, req.(*VMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMManager_SendQMPCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QMPCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMManagerServer).SendQMPCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMManager_SendQMPCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMManagerServer).SendQMPCommand(ctx, req.(*QMPCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMManager_ServiceDesc is the grpc.ServiceDesc for VMManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.VMManager",
	HandlerType: (*VMManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVM",
			Handler:    _VMManager_CreateVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _VMManager_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _VMManager_StopVM_Handler,
		},
		{
			MethodName: "GetVMStatus",
			Handler:    _VMManager_GetVMStatus_Handler,
		},
		{
			MethodName: "SendQMPCommand",
			Handler:    _VMManager_SendQMPCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcapi/vmmanager.proto",
}
