#!/usr/bin/perl
#LinodeConfigID=1
use 5.010;
use warnings;
use strict;
use BSD::Resource;
chmod 0440, '/linodes/linode506948/create.pl';
$SIG{INT} = 'IGNORE';
$ENV{PATH} = '';
$ENV{LD_PRELOAD} = '/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so:/usr/lib/x86_64-linux-gnu/nss/libfreeblpriv3.so';
require 'syscall.ph';
require 'sys/resource.ph';
setrlimit( RLIMIT_NOFILE, 65536, 1048576 );
my @cmd = (
	"/vbin/vcmd",
	"-d",
	"/usr/bin/nice",
	"-n",
	"1",
	"/opt/qemu-7.2.13-1-rbd/bin/qemu-system-x86_64",
	"-pidfile",
	"/linodes/linode506948/run/qemu.pid",
	"-chroot",
	"/linodes/linode506948/jail",
	"-nographic",
	"-cpu",
	"host,migratable=yes,-vmx,-svm,invpcid=off",
	"-display",
	"vnc=unix:/linodes/linode506948/run/vnc.socket",
	"-chardev",
	"socket,id=charmonitor,path=/linodes/linode506948/run/qemu.monitor,server,nowait,logfile=/linodes/linode506948/run/qemu_mon.log,logappend=off",
	"-mon",
	"chardev=charmonitor,id=monitor,mode=control",
	"-chardev",
	"socket,id=charhmpmonitor,path=/linodes/linode506948/run/qemu_hmp.monitor,server,nowait,logfile=/linodes/linode506948/run/qemu_hmp.log,logappend=off",
	"-mon",
	"chardev=charhmpmonitor,id=hmpmonitor",
	"-enable-kvm",
	"-name",
	"linode506948,debug-threads=on",
	"-runas",
	"linode506948",
	"-m",
	"1024M",
	"-smp",
	"1",
	"-rtc",
	"clock=vm",
	"-no-user-config",
	"-nodefaults",
	"-msg",
	"timestamp=on",
	"-smbios",
	"type=0,vendor=Linode,version=Not Specified",
	"-smbios",
	"type=1,manufacturer=Linode,product=Compute Instance,version=Not Specified,family=Linode.g6-nanode-1,serial=506948",
	"-machine",
	"q35,accel=kvm",
	"-vga",
	"std",
	"-kernel",
	"/vbin/kernel/grub-2.02-18-linode.img",
	"-device",
	"virtio-scsi-pci,id=scsi0",
	"-drive",
	"file=/dev/vg90/linode506948-25670,if=none,media=disk,id=drive-scsi-disk-0,aio=native,cache.direct=on,format=raw,read-only=off,auto-read-only=off",
	"-device",
	"scsi-hd,bus=scsi0.0,scsi-id=0,channel=0,lun=0,drive=drive-scsi-disk-0,id=drive0,bootindex=1,rotation_rate=1",
	"-device",
	"virtio-scsi-pci,id=scsi1",
	"-drive",
	"file=/dev/vg90/linode506948-25671,if=none,media=disk,id=drive-scsi-disk-1,aio=native,cache.direct=on,format=raw,read-only=off,auto-read-only=off",
	"-device",
	"scsi-hd,bus=scsi1.0,scsi-id=1,channel=0,lun=2,drive=drive-scsi-disk-1,id=drive1,rotation_rate=1",
	"-device",
	"virtio-scsi-pci,id=scsi2",
	"-drive",
	"file=rbd:block-volumes/3:id=bs-cph5:auth_supported=cephx;none:mon_host=[2600\\:3c1f\\:ffff\\:baca\\:cebb\\:\\:13]:rbd_cache=true:rbd_cache_size=32000000,if=none,media=disk,id=hpb_vol_1,aio=native,cache=writeback,format=rbd,throttling.bps-total=1048576000,throttling.iops-total-max=1500,throttling.iops-total-max-length=60,throttling.iops-total=500,read-only=off,auto-read-only=off",
	"-device",
	"scsi-hd,bus=scsi2.0,scsi-id=2,channel=0,lun=3,drive=hpb_vol_1,id=dev_bs_3,vendor=Linode,product=Volume,rotation_rate=1",
	"-device",
	"virtio-scsi-pci,id=scsi3",
	"-drive",
	"file=rbd:block-volumes/4:id=bs-cph5:auth_supported=cephx;none:mon_host=[2600\\:3c1f\\:ffff\\:baca\\:cebb\\:\\:13]:rbd_cache=true:rbd_cache_size=32000000,if=none,media=disk,id=hpb_vol_2,aio=native,cache=writeback,format=rbd,throttling.bps-total=1048576000,throttling.iops-total-max=1500,throttling.iops-total-max-length=60,throttling.iops-total=500,read-only=off,auto-read-only=off",
	"-device",
	"scsi-hd,bus=scsi3.0,scsi-id=3,channel=0,lun=4,drive=hpb_vol_2,id=dev_bs_4,vendor=Linode,product=Volume,rotation_rate=1",
	"-device",
	"virtio-scsi-pci,id=scsi4",
	"-drive",
	"file=rbd:block-volumes/5:id=bs-cph5:auth_supported=cephx;none:mon_host=[2600\\:3c1f\\:ffff\\:baca\\:cebb\\:\\:13]:rbd_cache=true:rbd_cache_size=32000000,if=none,media=disk,id=hpb_vol_3,aio=native,cache=writeback,format=rbd,throttling.bps-total=1048576000,throttling.iops-total-max=1500,throttling.iops-total-max-length=60,throttling.iops-total=500,read-only=off,auto-read-only=off",
	"-device",
	"scsi-hd,bus=scsi4.0,scsi-id=4,channel=0,lun=5,drive=hpb_vol_3,id=dev_bs_5,vendor=Linode,product=Volume,rotation_rate=1",
	"-append",
	" console=tty1 console=ttyS0 ro  devtmpfs.mount=1",
	"-no-reboot",
	"-netdev",
	"tap,id=net0,ifname=tap.506948_0,script=no,downscript=no,vhost=on,queues=8",
	"-device",
	"virtio-net-pci,netdev=net0,mac=f2:3c:93:6e:12:22,vectors=18,mq=on",
	"-parallel",
	"none",
	"-serial",
	"chardev:serial0",
	"-chardev",
	"stdio,mux=off,id=serial0,signal=off",
	"-D",
	"/linodes/linode506948/run/qemu-debug.log",
	"-d",
	"unimp"
);
close STDERR;
open (STDERR, '>', '/linodes/linode506948/run/qemu-stderr.log');
exec(@cmd) or die("couldnt exec ".join(" ",@cmd).": $!");