// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/vmmanager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VMManager_HandleControlEvents_FullMethodName = "/proto.VMManager/HandleControlEvents"
)

// VMManagerClient is the client API for VMManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VMManagerClient interface {
	HandleControlEvents(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error)
}

type vMManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewVMManagerClient(cc grpc.ClientConnInterface) VMManagerClient {
	return &vMManagerClient{cc}
}

func (c *vMManagerClient) HandleControlEvents(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMResponse)
	err := c.cc.Invoke(ctx, VMManager_HandleControlEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMManagerServer is the server API for VMManager service.
// All implementations must embed UnimplementedVMManagerServer
// for forward compatibility.
type VMManagerServer interface {
	HandleControlEvents(context.Context, *VMRequest) (*VMResponse, error)
	mustEmbedUnimplementedVMManagerServer()
}

// UnimplementedVMManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMManagerServer struct{}

func (UnimplementedVMManagerServer) HandleControlEvents(context.Context, *VMRequest) (*VMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleControlEvents not implemented")
}
func (UnimplementedVMManagerServer) mustEmbedUnimplementedVMManagerServer() {}
func (UnimplementedVMManagerServer) testEmbeddedByValue()                   {}

// UnsafeVMManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMManagerServer will
// result in compilation errors.
type UnsafeVMManagerServer interface {
	mustEmbedUnimplementedVMManagerServer()
}

func RegisterVMManagerServer(s grpc.ServiceRegistrar, srv VMManagerServer) {
	// If the following call pancis, it indicates UnimplementedVMManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMManager_ServiceDesc, srv)
}

func _VMManager_HandleControlEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMManagerServer).HandleControlEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMManager_HandleControlEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMManagerServer).HandleControlEvents(ctx, req.(*VMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMManager_ServiceDesc is the grpc.ServiceDesc for VMManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VMManager",
	HandlerType: (*VMManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleControlEvents",
			Handler:    _VMManager_HandleControlEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vmmanager.proto",
}
